spring:
  application:
    name: voley
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/voley?serverTimezone=America/Lima&useSSL=TRUE
    url: ${MYSQLHOST}
    #username: root
    username: ${MYSQLUSER}
    #password: raticate2024
    password: ${MYSQLPASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME:levidiaz2209@gmail.com}
    password: ${MAIL_PASSWORD:taptlqozuyaivgdh}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  #port: 8000
  port: ${PORT}

logging:
  level:
    org.hibernate.sql: debug